apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAuNHGzZ1D6Xrz3ygbcJq4pcD6BXBAFnO6njOTrMZu8dzqzaVu7qG9Ncfu27xu3ZesLrGxR3U7yCyugKAjvvz/MoK8rAWH9LR/To/4003e7t+B9MgqdUodHTSFI1QaVDGWeySM5h/tBMUUnnsy+NLvS4LJpgtY6xlf1N4xsmFGc0JqfrX+iyqJVtN+GN5FRFl3KGn6vnLnkgx+sDWNquNbrV3/VYoq9hM7UZkk7MUzUxl/Z4luDgpHZ3i3jfdlzmpcBa6WpafemzCY5FMq09xhLQCIYCeQT2t4jBppC0DfGyzC6EHrDd38R4ny0oHBETygZC4nx3S4gBndS6M8o/uEIt6U3y7qtqPxB/zv/DH9PnK/zCVAZ17kkQ/RQJkJRYZxEinWZ/WYWnyewavuz/DedxFzvDYqZMD3Oio2aOD5zDfP0wTgwLhAEpgLAPneRzlmM7aLZxN9yteqa8+6u6ThKQkvSCSL/7VRCngGkQT4RwVAFsAispVhbU/8D9UrecY4i80ZMPMondWCS3jo8KgHn7TqrGCjofaSDZsjrxC8H7sKlGZa028fXuG3TqTNgxOXijP2vNVKu6hQj+JjPBRlPf5dWDOQc31nYiN5z4yOjXWF+jRRbUA60qn67bIII6AZhT3V7yuhfK2jom8lOdgNA6nVESOAAt87n+hhujVhw9dUeB7oYo+kLVi4SZnRG78s5GT594Rp837g1dPabDFXXaq2+lWH0aMNxYfDy9ASgrmP71lScpLWvVvv526mYwAsPzaKmoLRdP4URA/DRf52m4bfM6l7N19tLmXAlRyOArE1UW/xuKuRAj95jfPrCc5bmQA6WsyvRcMZkR+fL0DUwa4Rthjqhkxmi7Xq6n9n9/iybV7/c/NGXuwlFLfcCWTKMYGjwT6H04p+7MtQ4oRcc+HGZE3sy8mRrFfxt9rONsWVuruZ9t9/nvh61mDCJJv4=
    IBM_ENTITLED_REGISTRY_USER: AgDJ/D+71ISj8VAG1BaMtaBHeGqiX1MUQQ2XN2v+EBB+Ul/ywQKxzyApLySVc0XbBoXADOH57UA3iHdO2DoNm5mk+MLV9Hvfv0R0cPI9iD6tdgkEqHNuflRdrV/CZ6nuqTaWvslN3okoiGEYZ5YoumbtvPzw164PZBwq+wjj1dxtzERoCgpz54/gAz0VlEhWimnMF0D7H+SBsZ5uojNbEW3mXU2QuwJQMlO539EtyXW6z9+9YkvO3rtzVBGV1sxgXvj4GBhLYtVyOjmcl3iLNzYzJiXqasVlMbsgF2irpzW6m2LLSR+ixr0E1VB98KQkmBXv7OteSw5Lu7i0iPnNwdwT4uPwAzV3dNAH/dYwbcF6SSIr7u49gJO5OhLxjsLQKMC6QLB+SpUmfO5jMbRn/0GaiZME+D3L4jqME2lgdMmFKxDPWOUT6ukSg6HsYSZIEJrVWrmUHDto9OA3v7ZR3PbMUJssNaWUdJjcV5UIF8Bn+E/OR1rsy2+edPQMdTrfHaMOwv46EQ4qw5DNEeMqk7Sv9BT/jRRXCqwbjGBi+PPzwNmDcUCY4wxQHB66XEZxQ4tSBoFCofm36pHYd7oifJTPjVKF7Ko+xDe3cc3K6gq4dfGQk0RNMXqZG0VsEioeDQoIUl8oYQc+bG4gYhOpNiwx3UFLx3LMmRQAHYqiNJ+SCuY8VR5hDeyiAsTx+jZxO+5plg==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

